name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.4
    - name: Build Docker Image
      run: docker build -t asrinibash/myrepo:${{ github.sha }} .
    - name: Push Docker Image
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && docker push asrinibash/myrepo:${{ github.sha }}
